name: Deploy wordpress EC2 with notification

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: credentials_setup
        uses: aws-actions/configure-aws-credentials@v3
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1

      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ./packer/aws-ami-wordpress.pkr.hcl

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./packer/aws-ami-wordpress.pkr.hcl

      - name: Build AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: ./packer/aws-ami-wordpress.pkr.hcl
          environment_vars: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
