name: Deploy wordpress EC2 with notification

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: credentials_setup
        uses: aws-actions/configure-aws-credentials@v3
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
      - name: Run `packer init`
        id: init
        run: "packer init ./packer/aws-ami-wordpress.pkr.hcl"
      - name: Run `packer build`
        id: build
        run: "packer build -force -var 'db_user=${{ secrets.DB_USER }}' -var 'db_password= ${{ secrets.DB_PASSWORD }}' -var 'db_name=${{ secrets.DB_NAME }}' -var 'db_root_password=${{ secrets.DB_ROOT_PASSWORD }}' './packer/aws-ami-wordpress.pkr.hcl'"
