name: Deploy wordpress EC2 with notification

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: credentials_setup
        uses: aws-actions/configure-aws-credentials@v3
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: packer_setup
      - name: Validate packer config
        id: packer_validate
        run: "packer validate ./packer/aws-ami-wordpress.pkr.hcl"
      - name: Initialization packer
        id: packer_init
        run: "packer init ./packer/aws-ami-wordpress.pkr.hcl"
      - name: Build AMI
        id: packer_build
        run: "packer build -force -var 'db_user=${{ secrets.DB_USER }}' -var 'db_password= ${{ secrets.DB_PASSWORD }}' -var 'db_name=${{ secrets.DB_NAME }}' -var 'db_root_password=${{ secrets.DB_ROOT_PASSWORD }}' './packer/aws-ami-wordpress.pkr.hcl'"
      - name: Get AMI id
        id: get_ami_id
        run: echo "artifact_id=$(jq -r '.builds[0].artifact_id' manifest.json)" >> $GITHUB_ENV

      - name: Setup `terraform`
        uses: hashicorp/setup-terraform@v3
        id: terraform_setup
        with:
          terraform_version: 1.5.6
      - name: Validate terraform config
        id: terraform_validate
        run: "terraform validate ./terraform"
      - name: Initialization terraform
        id: terraform_init
        run: "terraform init ./terraform"
      - name: Create ec2 instance
        id: terraform_apply
        run: "terraform apply -auto-approve -var 'artifact_id=${{ env.artifact_id }}' ./terraform"